plugins {
    id 'java'
}

group = 'guru.qa'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    testImplementation 'com.codeborne:selenide:6.13.0'
    testImplementation 'io.appium:java-client:8.3.0'
    testImplementation 'org.aeonbits.owner:owner:1.0.12'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.9'
}

test {
    useJUnitPlatform()
    systemProperties(System.getProperties())
    def platform = System.getProperty('platform')
    if (platform == 'ios') {
        filter {
            includeTestsMatching '*IosSampleTest'
        }
    } else if (platform == 'android') {
        filter {
            includeTestsMatching '*AndroidSearchTest'
        }
    }
    testLogging {
        events 'passed', 'failed', 'skipped'
        exceptionFormat 'full'
    }
}
